# 1. The PageRank algorithm

Problem 1

In [4]:
with open('./matrix.txt', 'r') as myfile:
    for line in myfile:
        print(str(line))

From Node	To Node

0	7

1	0

3	0

3	2

3	6

4	0

4	5

4	6

5	0

5	6

6	0

7	0


In [3]:
line = '0\t4\n'
line.strip().split()

['0', '4']

In [36]:
import numpy as np
import scipy.linalg as la
def adjacency(filename, N):
    adj = np.zeros((N,N))
    with open(filename, 'r') as myfile:
        i = 0
        for line in myfile:
            if i > 0:
                line = line.strip().split()
                adj[int(line[0]),int(line[1])] = 1
            i += 1
    return adj

In [21]:
A = adjacency('./matrix.txt',8)

In [22]:
A

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Problem 2

In [56]:
def Kmat(A):
    n = A.shape[0]
    for i in range(n):
        if sum(A.T[:,i]) == 0:
            A[i,:] = np.ones((1,n))
    D = np.diag(sum(A.T))
    D = la.inv(D)
    K = (D @ A).T
    return K

In [57]:
Kmat(A)

array([[ 0.        ,  1.        ,  0.125     ,  0.33333333,  0.33333333,
         0.5       ,  1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.33333333,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.33333333,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.33333333,  0.33333333,
         0.5       ,  0.        ,  0.        ],
       [ 1.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]])

In [ ]:
Problem 3

In [114]:
import numpy as np
def steadyState(A, N = None, d = 0.85, tol = 1e-5 ):
    import numpy as np
    if N != None:
        A = A[:N,:N]
    n = A.shape[0]
    K = Kmat(A)
    I = np.eye(n)
    E = np.ones((n,n))
    B = d * K + (1-d)/n * E
    
    #p = np.ones((1,n)).T/n
    p = np.eye(n)[0,].T
    dist = 10
    i = 1
    while dist > tol:
        #print(p)
        np = B @ p
        dist = abs(la.norm(np - p))
        p = np
        i +=1
    print('Number of iterations: ' + str(i))
    return p
        
        

In [117]:
steadyState(A)

Number of iterations: 75


array([ 0.43869593,  0.02171029,  0.02786154,  0.02171029,  0.02171029,
        0.02786154,  0.04585394,  0.39459619])

In [ ]:
Problem 4

In [118]:
def steadyState_2(A, N = None, d = 0.85):
    import numpy as np
    if N != None:
        A = A[:N,:N]
    n = A.shape[0]
    K = Kmat(A)
    I = np.eye(n)
    E = np.ones((n,n))
    B = d * K + (1-d)/n * E
    
    m,n = np.shape(A)
    evals, evecs = la.eig(np.dot(np.conjugate(A).T, A))
    ind = evals.argsort()[::-1]
    evals = evals[ind]
    evecs = evecs[ind]
    p = la.solve(I-d*K, ((1-d)/n)*np.ones(n))
    return p
   
        

In [119]:
steadyState_2(A)

array([ 0.43869288,  0.02171029,  0.02786154,  0.02171029,  0.02171029,
        0.02786154,  0.04585394,  0.39459924])

In [ ]:
Problem 5

In [ ]:
Problem 1

In [ ]:
Problem 2

In [ ]:
Problem 3

In [ ]:
Problem 4

In [46]:
Problem 5

SyntaxError: invalid syntax (<ipython-input-46-f33f15fe6ebf>, line 1)

In [ ]:
Problem 6

In [ ]:
Problem 1

In [ ]:
Problem 2

In [ ]:
Problem 3

In [ ]:
Problem 4

In [ ]:
Problem 5

In [ ]:
Problem 6

In [47]:
Problem 7

SyntaxError: invalid syntax (<ipython-input-47-f33f15fe6ebf>, line 1)

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [48]:
Problem 1

SyntaxError: invalid syntax (<ipython-input-48-11ebd3707099>, line 1)

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1

In [ ]:
Problem 1