In [172]:
import numpy as np

# Lab 3: Introduction to Numpy

Problem 1: Multiply two given matrices

In [173]:
def p1p1(A,B):
    
    return A.dot(B)
A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7],[9, -3, -2, -3]])
p1p1(A, B)


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2: Multiply two given matrices

In [174]:
def p1p2(A):
    
    return - A.dot(A.dot(A)) + 9 * A.dot(A) - 15 * A

A =  np.array([[3, 1, 4], [1, 5, 9],[-5, 3, 1]])
p1p2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3: Initialize two matrices A, B without array and return ABA

In [175]:
def p1p3():
    A = np.triu(np.ones((7,7), dtype=np.int))
    B = 5 * np.ones((7,7), dtype=np.int) - 6 * np.tril(np.ones((7,7), dtype=np.int))
    return  A.dot(B.dot(A)).astype(np.int64)

p1p3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4: Write a function, such that given an array, it makes a copy and returns copy with all negative entries set to zero 

In [176]:
def p1p4(A):
    B = np.copy(A)
    neg = B < 0 
    B[neg] = 0
    return B


Problem 5: Stack given matrices

In [177]:
def p1p5(A, B, C):
    V1 = np.vstack([np.zeros((A.shape[1], A.shape[1]), dtype=np.int), A, B])
    V2 = np.vstack([A.T, np.zeros((A.shape[0], A.shape[0]), dtype=np.int), np.zeros((B.shape[0], A.shape[0]), dtype=np.int)])
    V3 = np.vstack([np.eye(B.shape[0]), np.zeros((A.shape[0], B.shape[0],), dtype=np.int), C ])
    M = np.hstack([V1, V2, V3])
    return M

A = np.array([[0, 2, 4],[1, 3, 5]])
B = (3 * np.triu(np.ones((3,3), dtype=np.int))).T
C = -2 * np.eye(3)

p1p5(A, B, C)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

Problem 6: Write a function such that, give a matrix, it returns a row-stochastic matrix by dividing each row by its sum

In [178]:
def p1p6(A):
    x = A.sum(axis=1) # this is a row vector (dividing by it divides rows)
    return (A.T/x).T

Problem 7: Write a function that returns the greatest product of four adjacent numbers in the same direction in the given grid

In [188]:
grid = np.load(r"/Users/Jan/Desktop/BootCamp2017/ProbSets/Comp/grid.npy")

def maxmult4(grid): 
    rmx = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    cmx = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    rdmx = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    ldmx = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
    return max(rmx,cmx,rdmx,ldmx)

print(maxmult4(grid))

70600674


# Lab 2: The Standard Library

Problem 1: Write a function that accepts a list of numbers as inputs, and returns a new list wiht the min, max, avg of the original list

In [181]:
def l2p1(v):
    return max(v), min(v), sum(v)/len(v)

l2p1([3, 1, 0])

(3, 0, 1.3333333333333333)

In [187]:
def l2p2():
    v = [False] * 5
    a = 3
    b = a
    b += 1
    v[0] = (b == a)
    a = 'a'
    b = a
    b += 'a'
    v[1] = (b == a)
    a = list([1, 2, 3, 4, 5])
    b = a
    b.append(1)
    v[2] = (b == a)
    a = (2, 3, 4, 5, 6)
    b = a
    b += (1,)
    v[3] = (b == a)
    a = {1: 'x', 2: 'b'}
    b = a
    b[1] = 'a'
    v[4] = (b == a)
    
    return print("The statement \"[numbers, strings, lists, tuples, dictionaries] are mutable\" is " + str(v) +", respectively.")

l2p2()

The statement "[numbers, strings, lists, tuples, dictionaries] are mutable" is [False, False, True, False, True], respectively.


Problem 3: Create a module called calculator.py. Write a function that returns the sum of two arguments, a function that returns the product of two arguments, and a function that returns the square root of a single argument. When the file is either run or imported, nothing should be executed.

In your main solutions file, import your new calculator module. Using only the function defined in the module, write a new funciton that calculates  the length of the hypotenuse of a right triangle given the lengths of the other two sides.

In [274]:
import calculator as calc

def hypothenuse(a, b):
    return calc.sqrt(calc.sum(calc.prod(a,a), calc.prod(b,b)))

hypothenuse(3, 4)

AttributeError: module 'calculator' has no attribute 'sqrt'

In [243]:
calc.prod?

Object `calc.prod` not found.


In [232]:
math?

In [241]:
math.sqrt?


5.0

NameError: name 'SUM' is not defined

In [199]:
import math
math.sqrt(25)

5.0

Problem 4: 

# Lab 4: Object-Oriented Programming

Problem 1:

In [247]:
class Backpack(object):
    """A Backpack object class. Has a name and a list of contents.
Attributes:
name (str): the name of the backpack's owner. contents (list): the contents of the backpack.
"""
    def __init__(self, name, color, max_size = 5):           # This function is the constructor.
        """Set the name and initialize an empty contents list.
Inputs:
name (str): the name of the backpack's owner.
        Returns:
            A Backpack object wth no contents.
"""
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents.""" 
        if len(self.contents) < 5:
            self.contents.append(item)
        else:
            print("No room!")
            
    def take(self, item):
        """Remove 'item' from the backpack's list of contents.""" 
        self.contents.remove(item)
        
    def dump(self):
        self.contents = []

def test_backpack():
    testpack = Backpack("Barry", "black")
    if testpack.max_size != 5:
        print("Wrong default max_size!")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print(testpack.contents)
    testpack.put("item1")
    testpack.put("item2")
    testpack.dump()
    print(testpack.contents)
    
test_backpack()
    
    

['pencil', 'pen', 'paper', 'computer']
No room!
[]


Problem 2:

In [250]:
# Inherit from the Backpack class in the class definition.
class Knapsack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class.
    A jetpack is smaller than a backpack and can be tied closed.
    Attributes:
    name (str): the name of the jetpack's owner.
    color (str): the color of the jetpack.
    max_size (int): the maximum number of items that can fit
         in the jetpack.
    contents (list): the contents of the backpack.
    fuel (float): how much fuel the jetpack carr
    """
    def __init__(self, name, color, max_size=2, fuel = 10):
        """Use the Backpack constructor to initialize the name, color,
        and max_size attributes, and adds the fuel attribute. A jetpack only holds 2 item by default
        instead of 5.

        Inputs:
            name (str): the name of the jetpack's owner.
            color (str): the color of the jetpack.
            max_size (int): the maximum number of items that can fit
                 in the jetpack. Defaults to 3.
        Returns:
              A jetpack object with no contents.
        """
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
        
        def put(self, item):
            """If the jetpack is untied, use the Backpack.put() method."""
            Backpack.put(self, item)
            
        def take(self, item):
            """If the jetpack is untied, use the Backpack.take() method."""
            if self.closed:
                print("I'm closed!") 
            else:
                Backpack.take(self, item)
                
        def dump(self):
            self.contents = []     
            self.fuel = 0
            
        def fly():
            fuel_needed = float(raw_input("How much fuel does the trip take?"))
            if self.fuel >= fuel_needed:
                print("Whooosh - Off we go!")
                self.fuel -= fuel_needed
            else:
                print("Not enough fuel")
                  

Problem 3:

In [272]:
class Backpack(object):
    """A Backpack object class. Has a name and a list of contents.
    Attributes:
    name (str): the name of the backpack's owner. 
    contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size = 5):           # This function is the constructor.
        """Set the name and initialize an empty contents list.
        Inputs:
        name (str): the name of the backpack's owner.
        Returns:
            A Backpack object wth no contents.
        """
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents.""" 
        if len(self.contents) < 5:
            self.contents.append(item)
        else:
            print("No room!")
            
    def take(self, item):
        """Remove 'item' from the backpack's list of contents.""" 
        self.contents.remove(item)
        
    def dump(self):
        self.contents = []

    def __eq__(self, other):
        nmeq = self.name == other.name 
        cleq = self.color == other.name
        cteq = len(self.contents) == len(other.contents)
        return  nmeq and cleq and cteq 
    def __str__(self):
        print("Owner:" + "\t" + "\t" + self.name  + "\n" +\
              "Color:" + "\t" + "\t" + self.color + "\n" +\
              "Size:" + "\t" + "\t" +  str(len(self.contents))  + "\n" +\
              "Max Size:" + "\t" +  str(self.max_size)  + "\n" +\
              "Contents:" + "\t" +  str(self.contents))

In [ ]:
testpack = Backpack("Barry", "black")
for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
str(testpack)

Problem 4:

In [ ]:
class cplxnum(object):
    """The complex numbers as a class.
    real (float):  the real part
    imag (float):  the imaginary part
    """
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
    
    
        
    

# Lab 6: Exceptions and File I/O

Problem 1:

Problem 2:

Problem 3:

Problem 4:

# Lab 13: Unit Testing In Python

Problem 1:

Problem 2:

Problem 3:

Problem 4: