In [99]:
import numpy as np

Problem 1: Multiply two given matrices

In [100]:
def p1p1(A,B):
    
    return A.dot(B)
A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7],[9, -3, -2, -3]])
p1p1(A, B)


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2: Multiply two given matrices

In [101]:
def p1p2(A):
    
    return - A.dot(A.dot(A)) + 9 * A.dot(A) - 15 * A

A =  np.array([[3, 1, 4], [1, 5, 9],[-5, 3, 1]])
p1p2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3: Initialize two matrices A, B without array and return ABA

In [102]:
def p1p3():
    A = np.triu(np.ones((7,7), dtype=np.int))
    B = 5 * np.ones((7,7), dtype=np.int) - 6 * np.tril(np.ones((7,7), dtype=np.int))
    return  A.dot(B.dot(A))

p1p3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4: Write a function, such that given an array, it makes a copy and returns copy with all negative entries set to zero 

In [103]:
def p1p4(A):
    B = np.copy(A)
    neg = B < 0 
    B[neg] = 0
    return B


Problem 5: Stack given matrices

In [104]:
def p1p5(A, B, C):
    V1 = np.vstack([np.zeros((A.shape[1], A.shape[1]), dtype=np.int), A, B])
    V2 = np.vstack([A.T, np.zeros((A.shape[0], A.shape[0]), dtype=np.int), np.zeros((B.shape[0], A.shape[0]), dtype=np.int)])
    V3 = np.vstack([np.eye(B.shape[0]), np.zeros((A.shape[0], B.shape[0],), dtype=np.int), C ])
    M = np.hstack([V1, V2, V3])
    return M

A = np.array([[0, 2, 4],[1, 3, 5]])
B = (3 * np.triu(np.ones((3,3), dtype=np.int))).T
C = -2 * np.eye(3)

p1p5(A, B, C)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

Problem 6: Write a function such that, give a matrix, it returns a row-stochastic matrix by dividing each row by its sum

In [105]:
def p1p6(A):
    x = A.sum(axis=1) # this is a row vector (dividing by it divides rows)
    return (A.T/x).T

Problem 7: Write a function that returns the greatest product of four adjacent numbers in the same direction

In [106]:
grid = np.load("grid.npy")


FileNotFoundError: [Errno 2] No such file or directory: 'grid.npy'