In [1]:
import numpy as np

# Lab 3: Introduction to Numpy

Problem 1: Multiply two given matrices

In [2]:
def p1p1(A,B):
    
    return A.dot(B)
A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7],[9, -3, -2, -3]])
p1p1(A, B)


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2: Multiply two given matrices

In [3]:
def p1p2(A):
    
    return - A.dot(A.dot(A)) + 9 * A.dot(A) - 15 * A

A =  np.array([[3, 1, 4], [1, 5, 9],[-5, 3, 1]])
p1p2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3: Initialize two matrices A, B without array and return ABA

In [4]:
def p1p3():
    A = np.triu(np.ones((7,7), dtype=np.int))
    B = 5 * np.ones((7,7), dtype=np.int) - 6 * np.tril(np.ones((7,7), dtype=np.int))
    return  A.dot(B.dot(A)).astype(np.int64)

p1p3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4: Write a function, such that given an array, it makes a copy and returns copy with all negative entries set to zero 

In [5]:
def p1p4(A):
    B = np.copy(A)
    neg = B < 0 
    B[neg] = 0
    return B


Problem 5: Stack given matrices

In [6]:
def p1p5(A, B, C):
    V1 = np.vstack([np.zeros((A.shape[1], A.shape[1]), dtype=np.int), A, B])
    V2 = np.vstack([A.T, np.zeros((A.shape[0], A.shape[0]), dtype=np.int), np.zeros((B.shape[0], A.shape[0]), dtype=np.int)])
    V3 = np.vstack([np.eye(B.shape[0]), np.zeros((A.shape[0], B.shape[0],), dtype=np.int), C ])
    M = np.hstack([V1, V2, V3])
    return M

A = np.array([[0, 2, 4],[1, 3, 5]])
B = (3 * np.triu(np.ones((3,3), dtype=np.int))).T
C = -2 * np.eye(3)

p1p5(A, B, C)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

Problem 6: Write a function such that, give a matrix, it returns a row-stochastic matrix by dividing each row by its sum

In [7]:
def p1p6(A):
    x = A.sum(axis=1) # this is a row vector (dividing by it divides rows)
    return (A.T/x).T

Problem 7: Write a function that returns the greatest product of four adjacent numbers in the same direction in the given grid

In [8]:
grid = np.load(r"/Users/Jan/Desktop/BootCamp2017/ProbSets/Comp/grid.npy")

def maxmult4(grid): 
    rmx = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    cmx = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    rdmx = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    ldmx = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
    return max(rmx,cmx,rdmx,ldmx)

print(maxmult4(grid))

70600674


# Lab 2: The Standard Library

Problem 1: Write a function that accepts a list of numbers as inputs, and returns a new list wiht the min, max, avg of the original list

In [9]:
def l2p1(v):
    return max(v), min(v), sum(v)/len(v)

l2p1([3, 1, 0])

(3, 0, 1.3333333333333333)

In [10]:
def l2p2():
    v = [False] * 5
    a = 3
    b = a
    b += 1
    v[0] = (b == a)
    a = 'a'
    b = a
    b += 'a'
    v[1] = (b == a)
    a = list([1, 2, 3, 4, 5])
    b = a
    b.append(1)
    v[2] = (b == a)
    a = (2, 3, 4, 5, 6)
    b = a
    b += (1,)
    v[3] = (b == a)
    a = {1: 'x', 2: 'b'}
    b = a
    b[1] = 'a'
    v[4] = (b == a)
    
    return print("The statement \"[numbers, strings, lists, tuples, dictionaries] are mutable\" is " + str(v) +", respectively.")

l2p2()

The statement "[numbers, strings, lists, tuples, dictionaries] are mutable" is [False, False, True, False, True], respectively.


Problem 3: Create a module called calculator.py. Write a function that returns the sum of two arguments, a function that returns the product of two arguments, and a function that returns the square root of a single argument. When the file is either run or imported, nothing should be executed.

In your main solutions file, import your new calculator module. Using only the function defined in the module, write a new funciton that calculates  the length of the hypotenuse of a right triangle given the lengths of the other two sides.

In [11]:
import calculator as calc

def hypothenuse(a, b):
    return calc.root(calc.sum(calc.prod(a,a), calc.prod(b,b)))

hypothenuse(3, 4)

5.0

Problem 4: 

Solutions are in shutthebox.py 

# Lab 4: Object-Oriented Programming

Problem 1:

In [12]:
class Backpack(object):
    """A Backpack object class. Has a name and a list of contents.
Attributes:
name (str): the name of the backpack's owner. contents (list): the contents of the backpack.
"""
    def __init__(self, name, color, max_size = 5):           # This function is the constructor.
        """Set the name and initialize an empty contents list.
Inputs:
name (str): the name of the backpack's owner.
        Returns:
            A Backpack object wth no contents.
"""
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents.""" 
        if len(self.contents) < 5:
            self.contents.append(item)
        else:
            print("No room!")
            
    def take(self, item):
        """Remove 'item' from the backpack's list of contents.""" 
        self.contents.remove(item)
        
    def dump(self):
        self.contents = []

def test_backpack():
    testpack = Backpack("Barry", "black")
    if testpack.max_size != 5:
        print("Wrong default max_size!")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print(testpack.contents)
    testpack.put("item1")
    testpack.put("item2")
    testpack.dump()
    print(testpack.contents)
    
test_backpack()
    
    

['pencil', 'pen', 'paper', 'computer']
No room!
[]


Problem 2:

In [13]:
# Inherit from the Backpack class in the class definition.
class Knapsack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class.
    A jetpack is smaller than a backpack and can be tied closed.
    Attributes:
    name (str): the name of the jetpack's owner.
    color (str): the color of the jetpack.
    max_size (int): the maximum number of items that can fit
         in the jetpack.
    contents (list): the contents of the backpack.
    fuel (float): how much fuel the jetpack carr
    """
    def __init__(self, name, color, max_size=2, fuel = 10):
        """Use the Backpack constructor to initialize the name, color,
        and max_size attributes, and adds the fuel attribute. A jetpack only holds 2 item by default
        instead of 5.

        Inputs:
            name (str): the name of the jetpack's owner.
            color (str): the color of the jetpack.
            max_size (int): the maximum number of items that can fit
                 in the jetpack. Defaults to 3.
        Returns:
              A jetpack object with no contents.
        """
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
        
        def put(self, item):
            """If the jetpack is untied, use the Backpack.put() method."""
            Backpack.put(self, item)
            
        def take(self, item):
            """If the jetpack is untied, use the Backpack.take() method."""
            if self.closed:
                print("I'm closed!") 
            else:
                Backpack.take(self, item)
                
        def dump(self):
            self.contents = []     
            self.fuel = 0
            
        def fly():
            fuel_needed = float(raw_input("How much fuel does the trip take?"))
            if self.fuel >= fuel_needed:
                print("Whooosh - Off we go!")
                self.fuel -= fuel_needed
            else:
                print("Not enough fuel")
                  

Problem 3:

In [14]:
class Backpack(object):
    """A Backpack object class. Has a name and a list of contents.
    Attributes:
    name (str): the name of the backpack's owner. 
    contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size = 5):           # This function is the constructor.
        """Set the name and initialize an empty contents list.
        Inputs:
        name (str): the name of the backpack's owner.
        Returns:
            A Backpack object wth no contents.
        """
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents.""" 
        if len(self.contents) < 5:
            self.contents.append(item)
        else:
            print("No room!")
            
    def take(self, item):
        """Remove 'item' from the backpack's list of contents.""" 
        self.contents.remove(item)
        
    def dump(self):
        self.contents = []

    def __eq__(self, other):
        nmeq = self.name == other.name 
        cleq = self.color == other.name
        cteq = len(self.contents) == len(other.contents)
        return  nmeq and cleq and cteq 
    
    #def __str__(self):
    #    return "Owner:" + '\t'+ self.name + "\nColor:\t" +self.color+  "\nSize: \t"+ str(len(self.contents)) + "\nMax Size:\t" + str(self.max_size) + "\nContents:\t" + str(self.contents)

    def __str__(self):
        print("Owner:" + "\t" + "\t" + self.name + "\n" +\
            "Color:" + "\t" + "\t" + self.color + "\n" +\
            "Size:" + "\t" + "\t" +  str(len(self.contents))  + "\n" +\
            "Max Size:" + "\t" +  str(self.max_size)  + "\n" +\
            "Contents:" + "\t" +  str(self.contents))
        return ''
       

In [15]:
testpack = Backpack("Barry", "black")
for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
str(testpack)

Owner:		Barry
Color:		black
Size:		4
Max Size:	5
Contents:	['pencil', 'pen', 'paper', 'computer']


''

Problem 4:

In [ ]:

class ComplexNumber(object):
    """The complex numbers as a class.
    real (float):  the real part
    imag (float):  the imaginary part
    """
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
        
    def conjugate(self):
        conj = ComplexNumber(self.real, -self.imag)
        return conj
    
    def __abs__(self):
        from math import sqrt
        a = self.real
        b = self.imag
        return sqrt(a*a + b*b)
    
    def __lt__(self, other):
        return (abs(self) < abs(other))
    
    def __gt__(self, other):
        return (abs(self) > abs(other))
    
    def __eq__(self, other):
        eqre = (self.real == other.real)
        eqim = (real.imag == other.imag)
        return eqre and eqim
    
    def __ne__(self, other):
        eqre = (self.real == other.real)
        eqim = (real.imag == other.imag)
        return not (eqre and eqim)
        
    def __add__(self, other):
        adre = self.real + other.real
        adim = self.imag + other.imag
        return ComplexNumber(adre, adim)
    
    def __sub__(self, other):
        subre = self.real - other.real
        subim = self.imag - other.imag
        return ComplexNumber(subre, subim)
    
    def __mul__(self, other):
        mulre = self.real * other.real - self.imag * other.imag
        mulim = self.real * other.imag + other.real * self.imag
        return ComplexNumber(mulre, mulim)
    
    def inv(self):
        return self.conjugate() * (ComplexNumber(1 / (abs(self)* abs(self)), 0))
    
    def __truediv__(self, other):
        orinv = other.inv()
        return self * orinv
    
#x = ComplexNumber(3,4)
#y = ComplexNumber(5,12)
##z = ComplexNumber(3,4)
#abs(x)
#cx = x.conjugate()
#print(str(cx))
#cx.imag
#x.inv().real x.inv().imag
#(x.inv() * x).real
#(x / z).imag
#x == y
# Compare to built-in complex type?



# Lab 6: Exceptions and File I/O

Problem 1:

In [ ]:
import sys
def arithmagic():
    firstnumcorrect = False
    while firstnumcorrect == False:
        step_1 = int(input("Enter a 3-digit number where the first and last digits differ by 2 or more: "))
        lastdig = step_1 - (step_1 //10) * 10
        middig = step_1 - lastdig -(((step_1 // 10) // 10)*100)
        firstdig = (step_1 // 10) // 10
        if (type(step_1) != int) or (step_1 > 999) or (step_1<0):
            raise ValueError("Your input is not a three-digit number.")
        elif (abs(firstdig - lastdig) < 2):
            raise ValueError("Your first and last digit differ by less than two.")
        else: 
            correctstep_2 = lastdig * 100 + middig * 10 + firstdig
            print("Correct Step 2: " + str(correctstep_2))
            firstnumcorrect = True
            
    
    secnumcorrect = False
    while secnumcorrect == False:
        step_2 = int(input("Enter the reverse of the first number, obtained by reading it backwards: "))
        if step_2 != correctstep_2:
            raise ValueError("This is not the reverse of the first number.")
        else:
            correctstep_3 = abs(step_1 - step_2)
            lastdig3 = correctstep_3 - (correctstep_3 //10) * 10
            firstdig3 = (correctstep_3 // 10) // 10  
            middig3 = (correctstep_3 -(((correctstep_3 // 10) // 10)*100))//10
            print("middig3: "+ str(middig3))
            firstdig3 = (correctstep_3 // 10) // 10                 
            secnumcorrect = True
    
    thinumcorrect = False
    while thinumcorrect == False:
        step_3 = int(input("Enter the positive difference of these numbers: "))
        if step_3 != correctstep_3:
            raise ValueError("This is not the positive difference of the first two numbers.")
        else:
            correctstep_4 = lastdig3 * 100 + middig3 * 10 + firstdig3
            print("Correct Step 4: " + str(correctstep_4))
            thinumcorrect = True
                             
    founumcorrect = False
    while founumcorrect == False:
        step_4 = int(input("Enter the reverse of the previous result: "))
        if step_4 != correctstep_4:
            raise ValueError("This is not the reverse of the first number.")
        else: 
            founumcorrect = True
                             
    print(str(step_3) + " + " + str(step_4) + " = 1089 (ta-da!)")
arithmagic()


Problem 2:

In [ ]:
from random import choice
def random_walk(max_iters=1e12):
    walk = 0
    direction = [1, -1]
    try:
        for i in range(int(max_iters)):
            walk += choice(direction)
    except KeyboardInterrupt:
        print("Process interrupted at iteration " + str(i))
    else: 
        print("Process completed")
    finally:
        return walk
random_walk(2000000)

Problem 3:

In [ ]:
class ContentFilter():
    
    def __init__(self, filename):
        if type(filename) != str:
            raise TypeError("This is not a string.")
        self.name = filename
        # read in 
        contents = ""
        file = open(filename, 'r')
        lines = file.readlines()
        print(lines)
        for line in lines:
            contents += line
        self.contents = contents
        file.close()
        # print(file.closed) 
#test = ContentFilter(23)
test = ContentFilter("test.txt")
#test.name
#test.contents
"sgagda.dwwe"[-3:]

Problem 4:

In [ ]:
test.contents

In [ ]:
class ContentFilter():
    
    def __init__(self, filename):
        if type(filename) != str:
            raise TypeError("This is not a string.")
        self.name = filename
        contents = ""
        file = open(filename, 'r')
        lines = file.readlines()
        self.lines = lines
        for line in self.lines:
            contents += line
        self.contents = contents
        file.close()
        
    def uniform(self, newfilename, mode, case = "upper"):
        if mode != 'a' and mode != 'w':
            raise ValueError("This mode is not valid.")
        if newfilename[-4:] != ".txt":
            raise ValueError("New file name should be a .txt file")
        newfile = open(newfilename, mode)
        try:
            if case == "upper":
                for line in self.lines:
                    newfile.write(line.upper())
            elif case == "lower":
                for line in self.lines:
                    newfile.write(line.lower())
            else:
                raise ValueError("This is not an acceptable case.")
        finally:
            newfile.close()
        return 

    
    def reverse(self, newfilename, mode, unit = "line"):
        if mode != 'a' and mode != 'w':
            raise ValueError("This mode is not valid.")
        if newfilename[-4:] != ".txt":
            raise ValueError("New file name should be a .txt file")
        newfile = open(newfilename, mode)
        try:
            if unit == "line":
                for i in range(len(self.lines)):
                    newfile.write(lines[-(i+1)])
            elif unit == "word":
                for line in self.lines:
                    words = line[:-1].split(" ")
                    revwords = words[::-1]
                    newline = " ".join(revwords)
                    newfile.write(newline + "\n")
            else:
                raise ValueError("This is not an acceptable unit.")
        finally:
            newfile.close()
        return 
    
    def transpose(self, newfilename, mode, case = "upper"):
        import numpy as np
        if mode != 'a' and mode != 'w':
            raise ValueError("This mode is not valid.")
        if newfilename[-4:] != ".txt":
            raise ValueError("New file name should be a .txt file")
        newfile = open(newfilename, mode)
        matrix = []
        for line in self.lines:
            words = line[:-1].split(" ")
            matrix.append(words)
        npmatrix = np.array(matrix)
        transpose = npmatrix.T
        for row in transpose:
            newline = " ".join(row)
            print(newline)
            newfile.write(newline + "\n")
        newfile.close()
        return
    
    def __str__(self):
        print("Source file:" + "\t" + "\t" + self.name + "\n" +\
            "Total characters:" + "\t" + str(len(self.contents)) + "\n" +\
            "Alphabetic characters:" + "\t" +  str(sum(c.isalpha() for c in self.contents))  + "\n" +\
            "Numeric characters:" + "\t" +  str(sum(c.isdigit() for c in self.contents))  + "\n" +\
            "Whitespace characters:" + "\t" +  str(sum(c.isspace() for c in self.contents)) + "\n" +\
            "Number of lines:" + "\t" +  str(len(self.lines)))
        return ''
        
        
        # print(file.closed) 
#test = ContentFilter(23)
test = ContentFilter("test.txt")
str(test)
#test.uniform("test1.txt", 'w', "upper")
#test.reverse("test2.txt", 'w', "word")
#test.transpose("test3.txt", 'w', "word")
#test.name
#test.contents

# Lab 13: Unit Testing In Python

Lab 13 is in the test_solution.py file!

Problem 1:

In [1]:
import solutions as soln
hand = soln.Hand("Hand.txt")
#hand = Hand("Hand.txt")
print(hand.setcount())

2


Problem 2:

Problem 3:

Problem 4: